on: [push, pull_request]

name: Code

jobs:
  Code-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}

      - name: Install modules
        run: yarn

      - name: Lint code
        run: yarn lint

      - name: Test code
        run: yarn test
