on:
  release:
    types:
      - created

name: Deploy

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@trunkrs'

      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}

      - name: Install modules
        run: yarn

      - name: Build
        run: yarn build

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Apply version
        run: yarn apply-version ${{ steps.get_version.outputs.VERSION }}

      - name: Publish
        run: "cd publish && npm publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
